# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7112c221a7726658dbc5f7bbe7b2d9f8a1f26bc72b47aab313eff2b61b8c1ac9073bfabf8b5def2c0acab67b4df8a6b191bd172b0607b5ff6664b655416733f1

test:
  secret_key_base: 04ea17e780ecab0bf751b933fadcf7f8ca61b551a6d7db65ad66b9244cebdfb81bdbaa39517cf0ed1375e4eb3e773c5fd8c9229f01853c01104bc11b6eec914a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
